<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[createCustomer----> TestScript execution started]]>
    </line>
    <line>
      <![CDATA[--TestScript Execution skipped--]]>
    </line>
    <line>
      <![CDATA[createCustomer----> TestScript execution started]]>
    </line>
    <line>
      <![CDATA[--TestScript Execution skipped--]]>
    </line>
    <line>
      <![CDATA[createCustomer----> TestScript execution started]]>
    </line>
    <line>
      <![CDATA[--TestScript Execution failed--]]>
    </line>
  </reporter-output>
  <suite started-at="2023-01-12T17:29:46 IST" name="Suite" finished-at="2023-01-12T17:29:54 IST" duration-ms="7699">
    <groups>
    </groups>
    <test started-at="2023-01-12T17:29:46 IST" name="Test" finished-at="2023-01-12T17:29:54 IST" duration-ms="7699">
      <class name="com.cis.testng.scripts.CreateCustomerTestNG">
        <test-method is-config="true" signature="configDB()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:46 IST" name="configDB" finished-at="2023-01-12T17:29:46 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configDB -->
        <test-method is-config="true" signature="configBC()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:46 IST" name="configBC" finished-at="2023-01-12T17:29:49 IST" duration-ms="2329" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:49 IST" name="configBM" finished-at="2023-01-12T17:29:49 IST" duration-ms="417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="createCustomer()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:49 IST" name="createCustomer" finished-at="2023-01-12T17:29:50 IST" duration-ms="871" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.cis.testng.scripts.CreateCustomerTestNG.createCustomer(CreateCustomerTestNG.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createCustomer----> TestScript execution started]]>
            </line>
            <line>
              <![CDATA[--TestScript Execution skipped--]]>
            </line>
          </reporter-output>
        </test-method> <!-- createCustomer -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:50 IST" name="configAM" finished-at="2023-01-12T17:29:51 IST" duration-ms="549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:51 IST" name="configBM" finished-at="2023-01-12T17:29:51 IST" duration-ms="229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method retried="true" signature="createCustomer()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:51 IST" name="createCustomer" finished-at="2023-01-12T17:29:51 IST" duration-ms="507" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.cis.testng.scripts.CreateCustomerTestNG.createCustomer(CreateCustomerTestNG.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createCustomer----> TestScript execution started]]>
            </line>
            <line>
              <![CDATA[--TestScript Execution skipped--]]>
            </line>
          </reporter-output>
        </test-method> <!-- createCustomer -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:51 IST" name="configAM" finished-at="2023-01-12T17:29:52 IST" duration-ms="535" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:52 IST" name="configBM" finished-at="2023-01-12T17:29:52 IST" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="createCustomer()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:52 IST" name="createCustomer" finished-at="2023-01-12T17:29:53 IST" duration-ms="718" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.cis.testng.scripts.CreateCustomerTestNG.createCustomer(CreateCustomerTestNG.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[createCustomer----> TestScript execution started]]>
            </line>
            <line>
              <![CDATA[--TestScript Execution failed--]]>
            </line>
          </reporter-output>
        </test-method> <!-- createCustomer -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:53 IST" name="configAM" finished-at="2023-01-12T17:29:54 IST" duration-ms="535" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configAC()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:54 IST" name="configAC" finished-at="2023-01-12T17:29:54 IST" duration-ms="190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method is-config="true" signature="disconnectDB()[pri:0, instance:com.cis.testng.scripts.CreateCustomerTestNG@25fb8912]" started-at="2023-01-12T17:29:54 IST" name="disconnectDB" finished-at="2023-01-12T17:29:54 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disconnectDB -->
      </class> <!-- com.cis.testng.scripts.CreateCustomerTestNG -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
